version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3-stretch
        environment:
          - NODE_ENV: TEST
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn versions
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint all source files
          command: yarn lint
      - run:
          name: Build application
          command: yarn build
      - store_artifacts:
          path: ./dist
          destination: dist
  release:
    docker:
      - image: circleci/node:10.16.0-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Verify release, package, and deploy
          command: yarn semantic-release
      - store_artifacts:
          path: ./packages
          destination: packages

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
