version: 2.1
executors:
  base-executor:
    docker:
      - image: circleci/node:10.19.0-stretch
        environment:
          - NODE_ENV: TEST

commands:
  install_deps:
    description: 'Install node dependencies from the cache, and save the cache'
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  build:
    executor: base-executor
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run:
          name: Lint all source files
          command: yarn lint
      - run:
          name: Build application
          command: yarn build
      - store_artifacts:
          path: ./dist
          destination: dist
  release:
    executor: base-executor
    steps:
      - checkout
      - install_deps
      - run:
          name: Verify release, package, and deploy
          command: yarn semantic-release
      - store_artifacts:
          path: ./packages
          destination: packages

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
